services:
  humble_container:
    image: devcontainer:ros_humble
    container_name: devcontainer_ros
    build:
      context: .
      dockerfile: Humble.Dockerfile
      args:
        USERNAME: $USERNAME
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./shared:/shared:rw
      - ros_ws:/home/$USERNAME/ws:rw
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      DISPLAY: $DISPLAY
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - volume-init

  sgraphs:
    image: devcontainer_sgraphs:ros_humble
    container_name: devcontainer_ros_sgraphs
    build:
      context: .
      dockerfile: sgraphs.Dockerfile
      args:
        USECOLCON_JOBSRNAME: $USERNAME
        COLCON_JOBS: 10
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/media/pedros/smapper:/datasets
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true

  # Used to set correct U/G(ID) for shared folder
  volume-init:
    image: busybox
    command: ["chown", "-R", "1000:1000", "/shared"]
    volumes:
      - ./shared:/shared
    entrypoint: ""
    restart: "no"

volumes:
  ros_ws:
