services:
  humble_container:
    image: devcontainer/ros
    container_name: devcontainer/ros
    build:
      context: .
      dockerfile: Humble.Dockerfile
      args:
        USERNAME: $USERNAME
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./shared:/home/shared:rw
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      DISPLAY: $DISPLAY
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - volume-init

  # Used to set correct U/G(ID) for shared folder
  volume-init:
    image: busybox
    command: ["chown", "-R", "1000:1000", "/data"]
    volumes:
      - ./shared:/data
    entrypoint: ""
    restart: "no"
